### PR TITLE
Mapping updates

### PR DESCRIPTION
**Pull request by vaser888**
Changed some :::Warning:::  to :::Danger::: because the yellow for the Warning can be hard to read compared to either the green or the red.

Made it more clear for people to get into testplaying instead of being sandwiched in a weird location.

Updated how to zip a song in MMA2 to be able to send for a test play as well as added an image.

### CODE REVIEW

**Comment by vaser888** [comment]
I discovered that the nice big "Beginners guide" button on the front page of the wiki (not to mention, also on the top nav bar) has not been worked on in over a year and the page was basically empty. I took the liberty to make that button and area more helpful.

Added a bunch of information that could be helpful for a new user. Some of the writing should possibly be changed or added onto but I mostly spent today formatting it into a nice layout (at least I find it an acceptable layout)  and linking info to other areas of the wiki.

**Comment by bloodcloak** [comment]
I feel the info in the beginners page addition pertaining to maps, mods, and models is redundant/should be moved into the respective pages instead. 

I do like the addition of the Creating content addition to that page so that should be kept. 

Note though links to the readme for a section should not have the `readme.md` file name in the path. `./mapping/` instead of `./mapping/readme.md` for example as it automatically resolves to the readme at the root of the folder. This is for link consistency across the wiki and reduces the amount of characters utilized against the translation quota we have.

**Review by bloodcloak — CHANGES_REQUESTED** [review]
I feel the info in the beginners page addition pertaining to maps, mods, and models is redundant/should be moved into the respective pages instead.

I do like the addition of the Creating content addition to that page so that should be kept.

Note though links to the readme for a section should not have the readme.md file name in the path. ./mapping/ instead of ./mapping/readme.md for example as it automatically resolves to the readme at the root of the folder. This is for link consistency across the wiki and reduces the amount of characters utilized against the translation quota we have.

**Comment by vaser888** [comment]
I believe I fixed all the things you pointed out. 

I will be looking at maybe reworking the PC Modding page next week as it feels a little bit off to me.

**Review by bloodcloak — APPROVED** [review]

**Pull request merged**
