### PR TITLE
Update modders.md

### PR DESCRIPTION
**Pull request by sc2ad**
image
@lolPants

### CODE REVIEW

**Comment by Caeden117** [comment]
This looks good.

**Comment by Auros** [comment]
This looks good.

**Comment by nike4613** [comment]
This looks good.

**Comment by williums** [comment]
This looks good.

**Review by lolPants — APPROVED** [review]
This looks good.

**Review by bloodcloak — APPROVED** [review]
Approve

**Comment by RedBrumbler** [comment]
This looks good.

**Pull request merged**
