### PR TITLE
Add instructions for installing mods inside the Quest with QuestBoard

### PR DESCRIPTION
**Pull request by burritosoftware**
Small comment: To prevent conflicts with the permalinks to installing songs, I had to not use `Inside your Quest` or `Using your PC`, and instead I used other terms.

### CODE REVIEW

**Comment by bloodcloak** [comment]
The wiki compensates for duplicate anchors on the same page. You should be fine

**Comment by burritosoftware** [comment]
> The wiki compensates for duplicate anchors on the same page. You should be fine

What should I link to then if I want to refer to the first "Using your PC" section as a link then?

**Comment by bloodcloak** [comment]
How it does is by adding -# at the end of the duplicate anchor(s). With no effect on the first occurrence. See https://bsmg.wiki/about/event-winner.html for examples.

I also suggest you try setup and play around with a local build https://github.com/bsmg/wiki#-development

**Comment by burritosoftware** [comment]
I'll try a dev env, but I tried to edit the markdown with VSC without one as I only have like 4GBs of space left on my computer (lol)

But I'll try to take a look and modify it again

**Review by bloodcloak — APPROVED** [review]

**Pull request merged**
