### PR TITLE
Add Beataroni info

### PR DESCRIPTION
**Pull request by gary-kim**
Add information about Beataroni.

@geefr

### CODE REVIEW

**Comment by geefr** [comment]
Hey thanks for putting this together.

Info on beataroni is good, I may improve the ui/workflow but the instructions should remain valid for a long time.
(Couldn't get the images to load but assume it'll be right when merged/hosted)

While it's being changed, and assuming the maintainers agree I think these should also be done:
- Delete, archive, or collapse the section about using a virtual machine. I'm sure it'll work, but wouldn't recommend it
- In the section about wine it references BeatSaberModManager.exe, that's the old one, so that section could do with some updates
  - I think mod assistant does work under wine, as long as winetricks dotnet is setup, and the dll override is done. Haven't used mod assistant on linux myself though for a long time.

**Comment by Caeden117** [comment]
Another thing that could be considered: How about we bring the Linux modding guide out of the Modder's guide and into some part of the Beginner's Guide?

**Comment by bloodcloak** [comment]
That was something on my todo list after realizing it was more for playing than making mods on linux.

Still havent gotten to it because it needs an update away from the old mod manager.

Probably will hook onto this pr for that change when reviewing if someone else doesnt get to it before me

**Comment by gary-kim** [comment]
So, in that case, how about we separate the cleanup out into a second PR? I can start working on that once we merge this.

**Review by bloodcloak — APPROVED** [review]

**Pull request merged**
