### PR TITLE
Update quest-modding.md to include instructions for using ADB

### PR DESCRIPTION
**Pull request by DumbGameMaker**

### CODE REVIEW

**Comment by bloodcloak** [comment]
Is there a reason why someone would use ADB instead of SideQuest? I'm not that familiar with the quest modding scene.

**Comment by DumbGameMaker** [comment]
I mean, there exists full-on IDEs, but some people prefer to use VIM + gcc. There exists fancy WINE GUIs with additional comfort features and stuff, but some people prefer to use, or even self-compile, vanilla WINE or WINETweaks. And I promise you there is someone out there who is suspicious of SideQuest for some reason or just doesn't want to install something. (ADB comes as a zip of command-line utilities, SideQuest needs you to run an installer)

**Comment by DumbGameMaker** [comment]
Some people might already have ADB set up or in their `$PATH` and just don't wanna install something else when they already have something that works.

**Comment by bloodcloak** [comment]
Sorry for the delay. I see the reasoning now and have also checked with quest supports in the server. 

Will get to integrating this info soon. Just haven't been able to get around resolving the merge conflict and revising the structure to flow better for a general user.

**Pull request closed without merging**
