### PR TITLE
Updated steps and other info in PC Modding

### PR DESCRIPTION
**Pull request by overlappingd**
Adds "THIS IS THE RECOMMENDED DOWNGRADER." in BSManager's section in Installers. Also updates the Beta Downgrading steps to include the 1.34.2_legacy option, and fixes a typo in the Downgrading Section (Oculus downgrader to OculusDowngrader)

### CODE REVIEW

**Comment by overlappingd** [comment]
I've edited this PR to remove ModAssistant, as it is abandoned and has bugs. If needed, I can add it again and put a deprecation notice. BSManager will now state "THIS IS CURRENTLY THE RECOMMENDED MOD INSTALLER AND DOWNGRADER."

**Comment by overlappingd** [comment]
I've edited this PR to remove ModAssistant, as it is abandoned and has bugs.

**Comment by Meivyn** [comment]
This has been discussed and voted in overflow for the record.

**Comment by IAMDEDJUSTTOGETFILES** [comment]
I would keep the full name of the 1.29.1 legacy branch, as some people will probably need to find the exact name because that's how there minds work. Unless of course, the name has been changed. And if 1.34.2 also has a longer name, I would also fix it.

**Review by bloodcloak — CHANGES_REQUESTED** [review]
Would rather keep MA as a legacy option than outright delete

Keep the full branch name instead of truncate

**Comment by overlappingd** [comment]
> I would keep the full name of the 1.29.1 legacy branch, as some people will probably need to find the exact name because that's how there minds work. Unless of course, the name has been changed. And if 1.34.2 also has a longer name, I would also fix it.

hm, 1.34.2_legacy just has a dash and another 1.34.2_legacy to go along with it, so not sure about that. But I agree with you about the exact name of 1.29.1, I will extend that.

**Comment by overlappingd** [comment]
Requests fulfilled, also added a few more changes

**Comment by overlappingd** [comment]
Meivyn found a lot more outdated info on the Wiki, so they've decided to start a pull request on my branch, and I will be in touch to merging it in once it's ready.
https://github.com/overlappingd/wiki/pull/1

**Comment by bloodcloak** [comment]
Think be better merging in current changes and have the other update in a separate PR

**Comment by Meivyn** [comment]
I don't mind, however I don't see why you removed the warning about it being bugged. This might discourage users from using it *because* of that, which is the goal of that warning to begin with.

image

I've also updated the wording on my side. I agree with it being more generic though.

**Comment by bloodcloak** [comment]
Thought process was more of a nudge to start transitioning to a different tool.

BMBF's notice is more direct since it was fully dropped for not working at all rather than just having bugs. 
As far as Im aware, MA is still functional most of the time and the bugs have quick workarounds as more of an annoyance.

**Comment by overlappingd** [comment]
Undrafted, feel free to merge now!

**Review by overlappingd — COMMENTED** [review]
I don’t really care whether it’s a DANGER style or a WARNING styled window, the direct point is that MA is no longer recommended, and people should notice this and start moving to other mod installers to avoid bugs.

**Review by bloodcloak — APPROVED** [review]

**Pull request merged**
