### PR TITLE
Overhauled the '3d models' section of the site

### PR DESCRIPTION
**Pull request by legoandmars**
Up until now, the 3d modeling guides for sabers/platforms/avatars/notes have been externally hosted on bs.assistant.moe, making it difficult to people to contribute. I updated the guides to be on the site, and removed a lot of outdated information from the 3d model pages themselves.

I'll likely fix up the model guides and add a custom walls guide in the future.

### CODE REVIEW

**Review by lolPants — CHANGES_REQUESTED** [review]
needs rebasing on dce9487 and images moved to the new structure due to #212

**Comment by legoandmars** [comment]
rebased, ran optipng on images and moved them to the correct location

**Review by lolPants — CHANGES_REQUESTED** [review]
you seem to have duplicated images in both the old and new locations

**Comment by legoandmars** [comment]
I have no idea how that happened without me catching it, but it's fixed now

**Review by lolPants — APPROVED** [review]
technical aspects are ok'd from me
can't vouch for the content though

**Comment by lolPants** [comment]
i would also request whoever merges this to squash and merge to avoid cluttering the history with a lot of deleted images, and unnecessary merge commits

**Review by eth-nn — APPROVED** [review]
Reviewed pages, nothing pops out to me. Content not verified but trust bobbie its accurate.

**Pull request merged**
